apiVersion: v1                              # Secret 用 v1 版本
kind: Secret                                # 這是一個 Secret（保險箱）
metadata:
  name: mongo-secret                        # 保險箱的名字
type: Opaque                                # 通用型保險箱
data:
  username: dXNlcm5hbWU=                    # 存入帳號（Base64）
  password: cGFzc3dvcmQ=                    # 存入密碼（Base64）